theme: jekyll-theme-cayman
title: ScalaQuest
description: An exam project. From UNIBO, for PPS and LSS courses, 2019-2020.
show_downloads: true
github:
  zip_url: https://github.com/scalaquest/PPS-19-ScalaQuest/releases/latest
  tar_url: https://github.com/scalaquest/PPS-19-ScalaQuest/releases/latest
plugins:
  - jekyll-seo-tag