package io.github.scalaquest.core.model.behaviorBased.commons

import io.github.scalaquest.core.model.behaviorBased.BehaviorBasedModel
import io.github.scalaquest.core.model.behaviorBased.commons.groundBehaviors.CommonGroundBehaviorsExt
import io.github.scalaquest.core.model.behaviorBased.commons.grounds.CommonGroundExt
import io.github.scalaquest.core.model.behaviorBased.commons.itemBehaviors.CommonItemBehaviorsExt
import io.github.scalaquest.core.model.behaviorBased.commons.items.CommonItemsExt
import io.github.scalaquest.core.model.behaviorBased.commons.reactions.CommonReactionsExt

/**
 * A mixable trait that contains a set of common [[BehaviorBasedModel.BehaviorBasedItem]],
 * [[BehaviorBasedModel.ItemBehavior]], [[BehaviorBasedModel.GroundBehavior]] of common use, some
 * common [[BehaviorBasedModel.Reaction]] generated by the Behaviours and a accessible point with a
 * mixin mechanism from the [[BehaviorBasedModel]].
 */
trait CommonsExt
  extends BehaviorBasedModel
  with CommonItemBehaviorsExt
  with CommonItemsExt
  with CommonGroundBehaviorsExt
  with CommonGroundExt
  with CommonReactionsExt
