package io.github.scalaquest.core.model.behaviorBased

/**
 * Contains a set of common [[BehaviorBasedModel.BehaviorBasedItem]],
 * [[BehaviorBasedModel.ItemBehavior]], [[BehaviorBasedModel.GroundBehavior]] of common use, some
 * common [[BehaviorBasedModel.Reaction]] generated by the Behaviours, some common messages, a
 * pusher for the String implementation and a accessible point with a mixin mechanism from the
 * [[BehaviorBasedModel]].
 *
 * Usage example:
 * {{{
 *   object MyModel extends BehaviorableModel with CommonsExt
 *
 *   import MyModel._
 *   val door = SimpleDoor(itemRef, SimpleRoomLink(...))
 * }}}
 */
package object commons {}
