name: Update Docs

# This workflow generates the Scaladoc on each push on main, and commits
# the updates into the gh-pages branch.defaults:

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Correctly fetches tags. Useful to indicate the
          # right current version into the scaladoc.
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Scaladoc
        run: |
          ./gradlew :core:scaladoc
          ./gradlew :cli:scaladoc

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Push Scaladoc to gh-pages
        run: |
          mkdir ./gh-pages/scaladoc
          mkdir ./gh-pages/scaladoc/core
          mkdir ./gh-pages/scaladoc/cli
          mv ./core/build/docs/scaladoc ./gh-pages/scaladoc/core
          mv ./cli/build/docs/scaladoc ./gh-pages/scaladoc/cli
          cd ./gh-pages
          git config user.name Docubot
          git config user.email github-actions@github.com
          git add ./scaladoc
          git commit -m "Update Scaladoc"
          git push
