name: Semantic Versioning with Gradle CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch

  push:
    branches:
      - feature/git-semver-releases-attempts

jobs:
  SemanticVersioning:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make version directory
        run: mkdir version

      - name: Create versioning file
        run: ./gradlew printGitSemVer > version/version.txt

      - name: Create variable with version
        id: version
        run: |
            echo "::set-output name=VERSION::$(printf '"%s" ' version/version.txt)"

      - name: Generate distributions
        run: ./gradlew distZip



      #- name: Archive generated file(s)
        #uses: actions/upload-artifact@v2
        #with:
          #name: generatedDistributions
          #path: |
           #./examples/escape-room/build/distributions


     # - name: Create Release
     #   id: create-release
     #   uses: actions/create-release@v1
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #   with:
     #     tag_name: reports-${{ steps.date.outputs.date }}
     #     release_name: Release ${{ steps.date.outputs.date }}
     #     draft: false
     #     prerelease: false

     # - name: Upload Release Assets
      #  uses: dwenegar/upload-release-assets@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    release_id: ${{ steps.create-release.outputs.id }}
      #    assets_path: report