name: Semantic Versioning with Gradle CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch

  push:
    branches:
      - feature/git-semver-releases-attempts

jobs:
  SemanticVersioning:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make version directory
        run: mkdir version

      - name: Create versioning file
        # :core: -> uses a "forced" submodule in order to print version once
        #--quiet -> doesn't print gradle logs
        #  awk   -> takes last part of a string
        run: |
         ./gradlew :core:printGitSemVer --quiet | awk '{print $NF}' > version/version.txt
         cat version/version.txt

      - name: Create variable with version
        id: version
        run: |
          echo "::set-output name=VERSION::$(cat version/version.txt)"

      - name: Generate distributions
        run: ./gradlew distZip


      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-release.outputs.id }}
          assets_path: ./examples/escape-room/build/distributions