name: Check with Gradle CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - feature/new-gradle-build #to be removed
  pull_request:
    branches:
      - main

jobs:

 Check:
  runs-on: ${{ matrix.os }}
  strategy:
    fail-fast: true
    matrix:
      os: [ ubuntu-latest, macOS-latest, windows-latest ]

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # The project uses java 11 (LTS) with scala 2.13
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # Use cache if available for Gradle
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-


    - name: Check and Test with Gradle
      run: ./gradlew check